export { whatsappBotService } from './whatsappBotService';
export type {
    WhatsAppBotConfig,
    WhatsAppLog,
    BotStatus,
    QRCodeResponse,
    SendManualPayload,
    SendAlertPayload,
    SendToGroupPayload,
    Turma,
    WhatsAppGroup,
    SendResult,
    ApiResponse,
    BulkImportRow,
    BulkImportResult,
    GroupCandidate,
    AddToGroupResult,
    SendProgress,
    AiMessageTom,
    AiMessageTipo,
    AiMessageRequest,
    AiMessageResponse,
} from './types';
